export const product = [
  {
    id: 1,
    name: 'Vivo S1',
    img:
      'https://cdn.shortpixel.ai/client/q_glossy,ret_img,w_301,h_301/https://www.azariatika.com/wp-content/uploads/2019/08/azariatika_Vivo_S1_forum_handphone_android.jpg',
    price: 'Rp3.500.000',
    location: 'Kab. Bandung',
    shop: 'Bandung Elektronik',
    terjual: 58,
    ulasan: 12,
    diskusi: 32,
    stok: 8,
    kondisi: 'Baru',
    berat: '500 gram',
    merk: 'Vivo',
    deskripsi:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kategori: 'electronic',
  },
  {
    id: 2,
    name: 'Playstasion 5',
    img:
      'https://images.bisnis-cdn.com/posts/2020/11/04/1313430/playstation-5.jpg',
    price: 'Rp10.000.000',
    location: 'Kota Surabaya',
    shop: 'Surabaya Elektronik',
    terjual: 58,
    stok: 8,
    ulasan: 12,
    diskusi: 32,
    kondisi: 'Baru',
    berat: '5 kilo',
    merk: 'Sony',
    deskripsi:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kategori: 'electronic',
  },
  {
    id: 3,
    name: 'Philips Air Fryer',
    img:
      'https://ecs7.tokopedia.net/img/cache/700/product-1/2019/9/2/66234059/66234059_0e8adc0d-1cae-4ffb-8e6e-dc920cca7b33_700_700',
    price: 'Rp2.500.000',
    location: 'Kota Cimahi',
    shop: 'Cimahi Elektronik',
    terjual: 58,
    stok: 8,
    ulasan: 12,
    diskusi: 32,
    kondisi: 'Baru',
    berat: '1 kilo',
    merk: 'Phillips',
    deskripsi:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kategori: 'electronic',
  },
  {
    id: 4,
    name: 'Gundam AF',
    img:
      'https://images-na.ssl-images-amazon.com/images/I/71SzkAE9OrL._AC_SY450_.jpg',
    price: 'Rp2.000.000',
    location: 'Kota Palembang',
    shop: 'Palembang Toys',
    terjual: 58,
    stok: 8,
    ulasan: 12,
    diskusi: 32,
    kondisi: 'Baru',
    berat: '900 gram',
    merk: 'Bandai',
    deskripsi:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kategori: 'others',
  },
  {
    id: 5,
    name: 'YNH Book',
    img: 'https://cf.shopee.co.id/file/d06900c7e6144938e598b7dbe4b72166',
    price: 'Rp45.000',
    location: 'Kota Solo',
    shop: 'Solo Book Store',
    terjual: 58,
    stok: 8,
    ulasan: 12,
    diskusi: 32,
    kondisi: 'Baru',
    berat: '400 gram',
    merk: 'Gramedia',
    deskripsi:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kategori: 'others',
  },
  {
    id: 6,
    name: 'Light Saber',
    img:
      'https://images-na.ssl-images-amazon.com/images/I/41rvYpkxkuL._AC_SL1000_.jpg',
    price: 'Rp4.000.000',
    location: 'Kota Bogor',
    shop: 'Bogor Toys',
    terjual: 58,
    stok: 8,
    ulasan: 12,
    diskusi: 32,
    kondisi: 'Baru',
    berat: '1 kilo',
    merk: 'Starwars',
    deskripsi:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kategori: 'others',
  },
  {
    id: 7,
    name: 'Basreng Maicih',
    img:
      'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//84/MTA-2611317/maicih_maicih-basreng-keripik-pedas-snack--100-g-_full02.jpg',
    price: 'Rp15.000',
    location: 'Kota Bandung',
    shop: 'Borma Bandung',
    terjual: 58,
    stok: 8,
    ulasan: 12,
    diskusi: 32,
    kondisi: 'Baru',
    berat: '200 gram',
    merk: 'Maicih',
    deskripsi:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kategori: 'culinary',
  },
  {
    id: 8,
    name: 'Yamato Sarden',
    img:
      'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full/MTA-6620584/yamato-sarden_surabaya---sarden-yamato-makanan-kaleng--155-g-_full25.jpg',
    price: 'Rp25.000',
    location: 'DKI Jakarta',
    shop: 'Toserba Jakarta',
    terjual: 58,
    stok: 8,
    ulasan: 12,
    diskusi: 32,
    kondisi: 'Baru',
    berat: '200 gram',
    merk: 'Yamato',
    deskripsi:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kategori: 'culinary',
  },
  {
    id: 9,
    name: 'Sosis Sapi Pronas',
    img:
      'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//108/MTA-8890649/pronas_pronas_sosis_sapi_kemasan_kaleng_325gr_full01_k9x8sfp1.jpg',
    price: 'Rp35.000',
    location: 'Bali',
    shop: 'Warung Bali',
    terjual: 58,
    stok: 8,
    ulasan: 12,
    diskusi: 32,
    kondisi: 'Baru',
    berat: '200 gram',
    merk: 'Pronas',
    deskripsi:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kategori: 'culinary',
  },
  {
    id: 10,
    name: 'Mens Distressed Jeans',
    img:
      'https://static.tokopedia.net/blog/wp-content/uploads/2019/05/1.-Celana-Nudie-Jeans-300x300.jpg',
    price: 'Rp1.500.000',
    location: 'Kota Bandung',
    shop: 'Bandung Store',
    terjual: 58,
    stok: 8,
    ulasan: 12,
    diskusi: 32,
    kondisi: 'Baru',
    berat: '500 gram',
    merk: 'Nudie',
    deskripsi:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kategori: 'Fashion',
  },
  {
    id: 11,
    name: 'Linen Kimono',
    img: 'https://cf.shopee.co.id/file/43f41ccf7e13372a3bc573faa6cbdd85',
    price: 'Rp350.000',
    location: 'Kota Semarang',
    shop: 'Semarang Store',
    terjual: 58,
    stok: 8,
    ulasan: 12,
    diskusi: 32,
    kondisi: 'Baru',
    berat: '300 gram',
    merk: 'Linen',
    deskripsi:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kategori: 'Fashion',
  },
  {
    id: 12,
    name: 'Hip-Hop Hoodie',
    img:
      'https://ae01.alicdn.com/kf/Hc4da1cbfc28f4f16889128b7860cd98bi/Hoodie-Sweatshirt-Mens-Hip-Hop-Pullover-Hoodies-Streetwear-Casual-Fashion-Clothes-colorblock-hoodie-cotton.jpg',
    price: '500.000',
    location: 'Kota Bogor',
    shop: 'Bogor Store',
    terjual: 58,
    stok: 8,
    ulasan: 12,
    diskusi: 32,
    kondisi: 'Baru',
    berat: '400 gram',
    merk: 'Equal',
    deskripsi:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    kategori: 'Fashion',
  },
];
