export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const ADJUST_QTY = 'ADJUST_QTY';
export const LOAD_CURRENT_ITEM = 'LOAD_CURRENT_ITEM';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const CHECKOUT_ACTION = 'CHECKOUT_ACTION';
