export const ADD_ITEM = 'ADD_ITEM';
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const ADJUST_QTY= 'ADJUST_QTY';
export const LOAD_CURRENT_ITEM= 'LOAD_CURRENT_ITEM';
export const ADD_TO_WISHLIST= 'ADD_TO_WISHLIST';


